idle_bg = "#000000"
idle_fg = "#ffffff"
info_bg = "#000000"
info_fg = "#ffffff"
good_bg = "#000000"
good_fg = "#ffffff"
warning_bg  = "#000000"
warning_fg  = "#ff0000"
critical_bg = "#000000"
critical_fg = "#ff0000"
separator = "│"
separator_bg = "#000000"
separator_fg = "#ffffff"

