[theme]
theme = "mytheme"

[[block]]
block = "custom"
shell = "sh"
interval = "once"
signal = 10
command = '''
MUTE="$(pactl get-source-mute @DEFAULT_SOURCE@ | awk "{print \$2}")"
VOL="$(pactl get-source-volume @DEFAULT_SOURCE@ | awk -F"/" "NR==1{gsub(/ /,\"\"); print \$2}")"
if [ "$MUTE" = "yes" ]; then
  echo "<span color='red'>MIC MUTED</span>"
else
  echo "MIC: $VOL"
fi
'''

[[block]]
block = "sound"
format = " VOL $volume | VOL MUTED "

[[block]]
block = "custom"
interval = 60
command = "awk '{h=int($1/3600); m=int(($1%3600)/60); printf \"UP %dh %dm\", h, m}' /proc/uptime"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%A %d/%m/%Y') "

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%I:%M %p') "

