#!/usr/bin/env bash

yay -Sy

updates=$(yay -Qu)
count=$(echo "$updates" | wc -l)

if [ -z "$updates" ]; then
    echo	
    echo " System: Up To Date"
    echo
else
    echo
    echo " System: $count Packages to Update"
    echo
    echo " Packages to update:"
    echo " $updates"
    echo
fi

