#!/usr/bin/env bash

GREEN="\033[32m"
RESET="\033[0m"
BOLD="\033[1m"

today=$(date +%-d)
month_year="$(date +"%B %Y")"

echo

cal -3 | awk -v tday="$today" -v my="$month_year" -v green="$GREEN" -v bold="$BOLD" -v reset="$RESET" '
BEGIN {
    getline header
    cols[1]=substr(header, 1, 22)
    cols[2]=substr(header, 23, 22)
    cols[3]=substr(header, 45)
    col=0
    for(i=1;i<=3;i++) if(index(cols[i], my)) col=i
    print cols[1] "  " cols[2] " " cols[3]
}
{
    l1 = substr($0,1,22)
    l2 = substr($0,23,22)
    l3 = substr($0,45)

    for(i=1;i<=3;i++) {
        pat = "(^| )" tday "($| )"
        if(i==col) {
            if(i==1) l1 = gensub(pat, "\\1" green bold tday reset "\\2", "g", l1)
            if(i==2) l2 = gensub(pat, "\\1" green bold tday reset "\\2", "g", l2)
            if(i==3) l3 = gensub(pat, "\\1" green bold tday reset "\\2", "g", l3)
        }
    }
    print l1 "  " l2 "  " l3
}
' | sed 's/^/  /'

echo

