#!/usr/bin/env bash
# Reset everything to default
sudo iptables -F
sudo iptables -t nat -F
sudo iptables -X
sudo iptables -t nat -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT

# Then restart Docker to restore its own rules
sudo systemctl restart docker
