#!/usr/bin/env bash

match_val="$1"
focused_workspace=$(swaymsg -t get_workspaces | jq -r \
	'.[] | select(.focused).name')
client_id=$(swaymsg -t get_tree | jq -r '
  	.. | 
	if (.class? // "" | ascii_downcase | test("'"${match_val,,}"'")) then "[class=" + .class + "]"
	elif (.instance? // "" | ascii_downcase | test("'"${match_val,,}"'")) then "[instance=" + .instance + "]"
	elif (.app_id? // "" | ascii_downcase | test("'"${match_val,,}"'")) then "[app_id=" + .app_id + "]"
	else empty end')

if [[ -z "$client_id" ]]; then
	# If not running, spawn the app in background
	"$match_val" &
	exit 0
fi

swaymsg $client_id move to workspace $focused_workspace
swaymsg $client_id focus
