#!/usr/bin/env bash

if [ $# -lt 3 ]; then
    echo "Usage: swaywait [property_key] [property_value] [sway_command]"
    echo "Example: swaywait con_id 12345 focus"
    exit 1
fi

USER_KEY="$1"
USER_VALUE="$2"
shift 2
COMMAND=("$@")

while true; do
    APP_TREE=$(swaymsg -t get_tree | jq --arg KEY "$USER_KEY" --arg VALUE "$USER_VALUE" '.. | objects | select(has($KEY) and .[$KEY] == $VALUE)')
    if [ -n "$APP_TREE" ]; then
        break
    fi
    sleep 0.5
done

swaymsg "[$USER_KEY=$USER_VALUE]" "${COMMAND[@]}"

